### ISSUE TITLE
Pre release Clang versions? like 14 and 15

### ISSUE THREAD

**Issue by ldeluigi** [shenxianpeng/clang-tools#19]
Is it possible to add even those?

**Comment by 2bndy5** [comment]
I don't see any pre-releases for v15. I do see pre-releases for v14 (latest RC2 published last week).

Generally, these docker images tend to install clang-tools from apt provided packages (`Ubuntu:latest`). I suppose it would be possible to directly get the pre-releases from [the LLVM github releases page](https://github.com/llvm/llvm-project/releases). However, keeping the pre-release versions up to date would require more frequent maintenance from @shenxianpeng.

Alternatively any version could be built from LLVM source code because each version has a dedicated branch for development. I also don't see a branch for 15.x either

**Comment by ldeluigi** [comment]
Ok. Version 15 should be the one on master, not event a rc currently

**Comment by ldeluigi** [comment]
I agree with you that it would require much more maintenance, so I'm closing this issue for now, thanks

**Comment by shenxianpeng** [comment]
I can get the package from [LLVM's GitHub release page](https://github.com/llvm/llvm-project/releases), in fact, v13 does that since I didn't find v13 in `ubuntu:latest`.

For v14 pre-release, it seems that no package (like `x86_64-linux-gnu-ubuntu`) supports popular Linux container images (pls correct me if I'm wrong). It may be available in the official v14 as it was in official v13.

I watched the LLVM release event and will add for v14 as soon as it appears.

**Comment by 2bndy5** [comment]
>For v14 pre-release, it seems that no package (like x86_64-linux-gnu-ubuntu) supports popular Linux container images (pls correct me if I'm wrong). 

I do see a release assets that targets `clang+llvm-14.0.0-rc2-powerpc64le-linux-ubuntu-18.04.5`, but nothing specifically for Ubuntu 20.04. I'm not sure if a specific Ubuntu 20.04 target is needed for v14.

**Comment by shenxianpeng** [comment]
> I do see a release asset that targets clang+llvm-14.0.0-rc2-powerpc64le-linux-ubuntu-18.04.5

This is a PowerPC asset that can not be distributed via a docker image.

**Comment by 2bndy5** [comment]
Oh. Is that a license stipulation or an actual implementation problem? I do hope the offerings get better for v14 stable release.

**Comment by shenxianpeng** [comment]
It's an implementation problem, it failed when I build clang+llvm-14.0.0-rc2-powerpc64le-linux-ubuntu-18.04.5 with Ubuntu docker image.

**Comment by 2bndy5** [comment]
Well, if they don't offer a release asset that we can use (when they publish v14 stable), then we might have to resort to building v14 from the source code. Unless you can find a more up-to-date PPA repo that will provide a pre-built package of clang-tools v14 (and possibly v13 or v15) for Ubuntu 20.04. But the PPA idea seems unlikely.

**Comment by shenxianpeng** [comment]
[clang-tools](https://hub.docker.com/r/xianpengshen/clang-tools) docker image already supports v14. @ldeluigi 
```
$ docker run xianpengshen/clang-tools:14 clang-format --version
clang-format version 14.0.0

$ docker run xianpengshen/clang-tools:14 clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 14.0.0
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: cascadelake
```
